aggregator:
  settings:
    best_state_path: save/best.pbuf
    db_store_rounds: 2
    init_state_path: save/init.pbuf
    last_state_path: save/last.pbuf
    rounds_to_train: 2
    write_logs: false
  template: openfl.component.aggregator.Aggregator
assigner:
  settings:
    task_groups:
    - name: train_and_validate
      percentage: 1.0
      tasks:
      - aggregated_model_validation
      - train
      - locally_tuned_model_validation
  template: openfl.component.RandomGroupedAssigner
collaborator:
  settings:
    db_store_rounds: 1
    delta_updates: false
    opt_treatment: RESET
  template: openfl.component.collaborator.Collaborator
compression_pipeline:
  settings: {}
  template: openfl.pipelines.NoCompressionPipeline
data_loader:
  template: src.dataloader.TemplateDataLoader
  settings:
    batch_size: 64
network:
  settings:
    agg_addr: localhost
    agg_port: 59588
    cert_folder: cert
    client_reconnect_interval: 5
    disable_client_auth: false
    hash_salt: auto
    tls: true
  template: openfl.federation.Network
task_runner:
  settings: {}
  template: src.taskrunner.TemplateTaskRunner
tasks:
  aggregated_model_validation:
    function: validate_task
    kwargs:
      apply: global
  locally_tuned_model_validation:
    function: validate_task
    kwargs:
      apply: local
  settings: {}
  train:
    function: train_task
    kwargs:
      epochs: 1
