name: Windows (latest)

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  pytest-coverage: # from pytest_coverage.yml
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        pip install -r requirements-test.txt
        pip install .
    - name: Test with pytest and report code coverage
      run: |
        coverage run -m pytest -rA
        coverage report